
<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
    <div class="modal-body">
        <div class="form-group">
            <label for="nome">Nome: </label>
            <input type="text" name="nome" placeholder="O seu nome" value="<?php echo $medico->getNome() ?>">
        </div>
        <div class="form-group">
            <label for="morada">Morada</label>
            <input type="text" name="morada" placeholder="O sua morada" value="<?php echo $medico->getMorada() ?>">
        </div>
        <div class="form-group">
            <label for="telefone">Telefone</label>
            <input type="telefone" name="telefone" value="<?php echo $medico->getTelefone() ?>">
        </div>
    </div>
    <input type="hidden" name="id_medico" value="<?php echo $medico->getId() ?>">
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">fechar</button>
        <button type="submit" class="btn btn-primary">criar</button>
    </div>
</form>